name = "NCBIBlast"
uuid = "dcaf3faf-48b5-45a7-abb1-fcfd75344536"
authors = ["Kevin Bonham <kevin@bonham.ch> and contributors"]
version = "0.1.0"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"

[compat]
CondaPkg = "0.2.23"
julia = "1.10"
